In [2]:
import pandas as pd
from pathlib import Path

**Extracting uniquerid from Namma Yatri data**

Skip below code if you already have exacted data ( as it takes around 45 mins to run below code)

In [ ]:
# BASE_DIR = Path("../Namma_yatri_data")
# OUTPUT_DIR = Path("../uniquerids")
# OUTPUT_DIR.mkdir(exist_ok=True)

# def process_folder(folder_path: Path, output_path: Path):
#     seen_rid = set()
#     rows = []

#     for file in sorted(folder_path.glob("*.parquet")):
#         df = pd.read_parquet(file)

#         # normalize rid
#         df["rid"] = df["rid"].astype(str)

#         # remove duplicates within the file
#         df = df.drop_duplicates(subset="rid", keep="first")

#         # remove duplicates across files
#         mask = ~df["rid"].isin(seen_rid)
#         filtered = df.loc[mask]

#         seen_rid.update(filtered["rid"].tolist())
#         rows.append(filtered)

#     if rows:
#         final_df = pd.concat(rows, ignore_index=True)
#         final_df.to_parquet(output_path, index=False)
#         print(f"Saved: {output_path} | rows={len(final_df)}")
#     else:
#         print(f"No parquet files in {folder_path}")


# # process each subfolder
# for subfolder in sorted(p for p in BASE_DIR.iterdir() if p.is_dir()):
#     output_file = OUTPUT_DIR / f"{subfolder.name}_unique_rid.parquet"
#     process_folder(subfolder, output_file)

**Combine 2 week uniquerid data**

Skip below code if you already have exacted data

In [ ]:
# INPUT_DIR = Path("../uniquerids")
# OUTPUT_FILE = Path("../combinedrids/combined_unique_rid.parquet")

# dfs = []

# for file in sorted(INPUT_DIR.glob("*.parquet")):
#     df = pd.read_parquet(file)

#     # normalize rid to be safe
#     df["rid"] = df["rid"].astype(str)

#     dfs.append(df)

# combined_df = pd.concat(dfs, ignore_index=True)

# # final global de-duplication (important)
# combined_df = combined_df.drop_duplicates(subset="rid", keep="first")

# combined_df.to_parquet(OUTPUT_FILE, index=False)

# print(f"Saved {len(combined_df)} rows to {OUTPUT_FILE}")

**Observe Combined data**

In [ ]:
output_file = "../combinedrids/combined_unique_rid.parquet" # change accordingly
combined_df = pd.read_parquet(output_file, engine="pyarrow")
combined_df

,rid,driver_id,ts,lat,lon,active,mode,rideStatus,vehicle_variant,rider_id,...,trip_start_time,trip_end_time,chargeable_distance,trip_start_lat,trip_start_lon,trip_end_lat,trip_end_lon,driver_arrival_time,hashed_driver_id,hashed_rid
0,000ff8fb-42f6-42c6-b2d1-d253d9d3f84b,33396cb5-ffd1-48d1-a623-2532a3e51204,2025-07-30 02:28:37.639,12.9692233,77.5246067,1,ONLINE,ON_PICKUP,AUTO_RICKSHAW,d865efa7-e800-4de0-baa4-517ad24794c8,...,2025-07-30 02:33:58,2025-07-30 03:16:33,19641.0,12.967007,77.521632,13.041285,77.619642,2025-07-30 02:33:45,4f174bf5f9c83f5d36b7a986601a994eb71eb2156ff45e...,791e3da60412a606a39be01a0e53f0dd8217f6fa0c1859...
1,001972ec-9ee6-47b3-9969-aab1b7f66408,628d10d2-7a45-4347-af2b-a1a50cf3f8b9,2025-07-30 13:03:13.470,12.960007,77.6492215,1,ONLINE,ON_PICKUP,AUTO_RICKSHAW,c154d0b7-2614-4b1e-8e02-4280baad034f,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,ffbeb11841e4ecb2a8ae686d5772bc6413443079d4aefc...,1af748b576e4796058c4ee86abd4d29ad59750bfe9d6e1...
2,001d8092-fa4b-45d7-8e26-77660761a1ab,99adbf05-9d87-418a-bdd1-8c011d136331,2025-07-30 11:59:42.577,12.9953033,77.5961117,1,ONLINE,ON_PICKUP,AUTO_RICKSHAW,bd84cf10-2a9c-43e2-922b-247e5def1388,...,2025-07-30 12:15:07,2025-07-30 13:11:29,14455.0,12.981527,77.597252,12.901654,77.539214,2025-07-30 12:10:26,3c6a15db3ef6cf7cd0e0681b7a8b75592bcedd0022f9b1...,524b2080d5a8ec3578ff05f2961094254b91c1087d06e3...
3,00201eca-7ff6-400e-9631-bbaee6dcc1b5,ccdabf71-ce3f-4007-961a-a1c4e13a2150,2025-07-30 11:35:26.364,13.02629,77.5316317,1,ONLINE,ON_PICKUP,AUTO_RICKSHAW,b34bedae-fe34-421d-9042-0b7972f92d30,...,2025-07-30 11:46:21,2025-07-30 12:46:05,16787.0,13.029167,77.540034,13.079102,77.633052,NaT,8fb140fe1ca2fb78ae5be9c6e6dbff912acb3ecc97d6f0...,830b84022e5af06037fcd07d96c5f48955e409759b50a8...
4,002f4519-d653-4f54-944c-6cc8028f8fdb,af73ee08-5a54-4d4d-8cdf-91478bfe107c,2025-07-30 06:55:01.141,13.0079501,77.6694977,1,ONLINE,ON_PICKUP,AUTO_RICKSHAW,1ad46be8-9007-4970-b97c-ace91831faa4,...,2025-07-30 07:01:46,2025-07-30 07:08:24,1306.0,13.012023,77.667913,13.017949,77.673293,2025-07-30 06:59:41,62c3f6e5997e027b10a1958aec48602db5d297a185718f...,c44b3043b35d7680c0847ab499caf10d00fab9a5ac38ff...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2416151,ffecc1f0-e0ae-4f16-a4ce-5fa083c980a9,ae6ccf3a-b753-4cea-93f8-49bf722129cf,2025-08-12 07:30:12.534,13.0677483,77.59856,1,ONLINE,ON_PICKUP,AUTO_RICKSHAW,9ec7e4b8-e300-47e2-bd6e-156eefc83d7c,...,2025-08-12 07:33:37,2025-08-12 07:46:30,4064.0,13.064868,77.596003,13.094877,77.594553,2025-08-12 07:33:30,fa560d9a9a8409d1e8e8e5c3ce61d15c4a6511bbcc9046...,abf50837314e05ce565da1311efe0a2f33e3fdb2ea1917...
2416152,fff41525-3efb-4226-926b-273c4f7aae11,96dc2571-b2c3-49e4-b78a-cb0a219814e8,2025-08-12 03:47:58.894,12.9368033,77.5740517,1,ONLINE,ON_PICKUP,AUTO_RICKSHAW,63f5d958-53ac-480e-94a9-4f352f1bf3db,...,2025-08-12 03:51:52,2025-08-12 04:21:01,7154.0,12.936313,77.574832,12.897510,77.598975,2025-08-12 03:50:36,e0898b4e85db419d024715b544adbfb6ce39409bac75fe...,16d4a5ac734682c5df2f4ec807ffd44f29b80232cb4613...
2416153,fff5b17f-c50d-4137-bf62-22ef42e6e592,8a3daf0f-3cac-4a7f-829c-29a9415702c7,2025-08-12 06:06:47.769,12.8836417,77.5500067,1,ONLINE,ON_PICKUP,AUTO_RICKSHAW,f61e25f7-7e3a-48e4-b94b-d44f0167e7a7,...,2025-08-12 06:11:51,2025-08-12 06:35:10,7029.0,12.882419,77.546706,12.906522,77.597740,2025-08-12 06:11:47,cd72b33a39cdeb0bcc0712cb233cad057cd726c34a6880...,a63648acf955cda62e6ff353b07000b8da474b0e12ddc3...
2416154,fffb9649-35a0-49f6-afef-4690ee5ae782,54aeddf5-b506-4bda-922c-63a0a43ebb58,2025-08-12 04:49:50.083,12.9250281,77.6339174,1,ONLINE,ON_PICKUP,AUTO_RICKSHAW,58a23329-7016-4a54-9a74-fdb8a695495f,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaT,793eb50dc2ab6969d5372d9eb446dd3ccb033e51555a2a...,2a363071229801ef347b226f516cf8c94c8b0d20ba493b...
2416155,ffff8150-e6a3-4820-9693-2d094eba7ce9,9513a522-4b10-49de-b7f0-0e7a30821865,2025-08-12 15:52:21.024,13.0111339,77.6622317,1,ONLINE,ON_PICKUP,AUTO_RICKSHAW,7d1b6828-0629-433a-9fdb-d6a33bff7198,...,2025-08-12 15:57:19,2025-08-12 16:14:30,4948.0,13.010440,77.660129,13.034241,77.641025,2025-08-12 15:56:27,a0c5965a7f7eab1164dba9dc676a9ad3115978ece0866f...,a21fb893e324729a95be4e1073959a9ccc154330baeaa1...

In [4]:
combined_df.nunique(dropna=True)

rid                    2416156
driver_id                75105
ts                     2410471
lat                    1207618
lon                    1208631
active                       1
mode                         3
rideStatus                   3
vehicle_variant              1
rider_id                720418
status                       4
fare                       934
traveled_distance       279382
trip_start_time         713388
trip_end_time           714855
chargeable_distance      32614
trip_start_lat          958228
trip_start_lon          956544
trip_end_lat            973872
trip_end_lon            972069
driver_arrival_time     634849
hashed_driver_id         75105
hashed_rid             2416156
dtype: int64

In [5]:
print(combined_df['mode'].value_counts())
print(combined_df['rideStatus'].value_counts())
print(combined_df['status'].value_counts())

mode
ONLINE     2407207
SILENT        8461
OFFLINE        488
Name: count, dtype: int64
rideStatus
ON_PICKUP    2349882
ON_RIDE        66273
IDLE               1
Name: count, dtype: int64
status
COMPLETED     1658091
CANCELLED      755092
INPROGRESS       2161
NEW               811
Name: count, dtype: int64

In [6]:
combined_df = combined_df[combined_df['status'] == "COMPLETED"]
combined_df = combined_df[combined_df['mode'] == "ONLINE"]

In [7]:
combined_df.nunique(dropna=True)

rid                    1653053
driver_id                71640
ts                     1649623
lat                     952299
lon                     949661
active                       1
mode                         1
rideStatus                   2
vehicle_variant              1
rider_id                624524
status                       1
fare                       932
traveled_distance       278698
trip_start_time         712082
trip_end_time           714246
chargeable_distance      32596
trip_start_lat          955557
trip_start_lon          953869
trip_end_lat            971925
trip_end_lon            970166
driver_arrival_time     616092
hashed_driver_id         71640
hashed_rid             1653053
dtype: int64

**Preprocess Combined data**

In [22]:
cols_to_keep = ['hashed_rid', 'hashed_driver_id', 'trip_start_lat', 'trip_start_lon', 'trip_end_lat', 'trip_end_lon', 'trip_start_time', 'trip_end_time', 'chargeable_distance', 'fare', 'traveled_distance','rider_id']
combined_df = combined_df[cols_to_keep]

In [27]:
combined_df = combined_df.dropna()

In [44]:
combined_df["chargeable_distance"]

0          19641.0
2          14455.0
3          16787.0
4           1306.0
5           4468.0
            ...
2416149     7038.0
2416151     4064.0
2416152     7154.0
2416153     7029.0
2416155     4948.0
Name: chargeable_distance, Length: 1652099, dtype: float64

In [28]:
combined_df.nunique(dropna=True)

hashed_rid             1652099
hashed_driver_id         71635
trip_start_lat          955557
trip_start_lon          953869
trip_end_lat            971519
trip_end_lon            969785
trip_start_time         712082
trip_end_time           714177
chargeable_distance      32590
fare                       931
traveled_distance       278403
rider_id                624329
dtype: int64

Save new combine data with required columns

In [29]:
OUTPUT_FILE = Path("./combinedrids/combined_unique_hashed_rid.parquet")
combined_df.to_parquet(OUTPUT_FILE, index=False)

print(f"Saved {len(combined_df)} rows to {OUTPUT_FILE}")

Saved 1652099 rows to combinedrids/combined_unique_hashed_rid.parquet

In [45]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1652099 entries, 0 to 2416155
Data columns (total 12 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   hashed_rid           1652099 non-null  object
 1   hashed_driver_id     1652099 non-null  object
 2   trip_start_lat       1652099 non-null  float64
 3   trip_start_lon       1652099 non-null  float64
 4   trip_end_lat         1652099 non-null  float64
 5   trip_end_lon         1652099 non-null  float64
 6   trip_start_time      1652099 non-null  datetime64[ns]
 7   trip_end_time        1652099 non-null  datetime64[ns]
 8   chargeable_distance  1652099 non-null  float64
 9   fare                 1652099 non-null  float64
 10  traveled_distance    1652099 non-null  float64
 11  rider_id             1652099 non-null  object
dtypes: datetime64[ns](2), float64(7), object(3)
memory usage: 163.9+ MB

In [30]:
rows_with_nulls = combined_df.isna().any(axis=1).sum()
rows_with_nulls

np.int64(0)

In [31]:
combined_df.isna().sum()

hashed_rid             0
hashed_driver_id       0
trip_start_lat         0
trip_start_lon         0
trip_end_lat           0
trip_end_lon           0
trip_start_time        0
trip_end_time          0
chargeable_distance    0
fare                   0
traveled_distance      0
rider_id               0
dtype: int64

**Make new seprate file to extact subpart of combined_unique_hashed_rid need for origns**

In [32]:
cols_to_keep_originlatlon = ['trip_start_lat', 'trip_start_lon']
originlatlon_df = combined_df[cols_to_keep_originlatlon]

In [33]:
originlatlon_df.nunique(dropna=True)

trip_start_lat    955557
trip_start_lon    953869
dtype: int64

In [34]:
originlatlon_df

         trip_start_lat  trip_start_lon
0             12.967007       77.521632
2             12.981527       77.597252
3             13.029167       77.540034
4             13.012023       77.667913
5             12.993979       77.577726
...                 ...             ...
2416149       12.972339       77.649057
2416151       13.064868       77.596003
2416152       12.936313       77.574832
2416153       12.882419       77.546706
2416155       13.010440       77.660129

[1652099 rows x 2 columns]

In [35]:
rows_with_nulls = originlatlon_df.isna().any(axis=1).sum()
rows_with_nulls

np.int64(0)

In [ ]:
OUTPUT_FILE = Path("../combinedrids/originlatlon_hashed_rid.parquet")
originlatlon_df.to_parquet(OUTPUT_FILE, index=False)

print(f"Saved {len(originlatlon_df)} rows to {OUTPUT_FILE}")

Saved 1652099 rows to combinedrids/originlatlon_hashed_rid.parquet

In [ ]:
read_file1 = "../combinedrids/originlatlon_hashed_rid.parquet" # change accordingly
originlatlon_df = pd.read_parquet(read_file1, engine="pyarrow")
originlatlon_df

         trip_start_lat  trip_start_lon
0             12.967007       77.521632
1             12.981527       77.597252
2             13.029167       77.540034
3             13.012023       77.667913
4             12.993979       77.577726
...                 ...             ...
1652094       12.972339       77.649057
1652095       13.064868       77.596003
1652096       12.936313       77.574832
1652097       12.882419       77.546706
1652098       13.010440       77.660129

[1652099 rows x 2 columns]

**Make new seprate file to extact subpart of combined_unique_hashed_rid need for destins**

In [46]:
cols_to_keep_destlatlon = ['trip_end_lat', 'trip_end_lon']
destlatlon_df = combined_df[cols_to_keep_destlatlon]

In [47]:
destlatlon_df.nunique(dropna=True)

trip_end_lat    971519
trip_end_lon    969785
dtype: int64

In [ ]:
OUTPUT_FILE = Path("../combinedrids/destlatlon_hashed_rid.parquet")
destlatlon_df.to_parquet(OUTPUT_FILE, index=False)

print(f"Saved {len(destlatlon_df)} rows to {OUTPUT_FILE}")

Saved 1652099 rows to combinedrids/destlatlon_hashed_rid.parquet